spring:
  profiles:
    active: local
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: crossfit
      port: 27017
      host: localhost