POST localhost:8080/test/workouts
Content-Type: application/json

{
  "id": 1,
  "athlete": 1,
  "wod": {
    "id": 1,
    "gymId": 10,
    "workout": "10R\n데드리프트 10개\n스쿼트 10개\n턱걸이 10개",
    "workoutDate": "2021-04-03T12:00:00",
    "workoutTypes": ["DEAD_LIFT", "SQUAT", "CHIN_UP"]
  },
  "record": "13분 5초",
  "likes": []
}